[build]
  command = "pnpm install && pnpm db:generate && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  PNPM_VERSION = "8"

# Remove custom redirects - let Next.js plugin handle API routes
[functions]
  directory = ".netlify/functions"

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development" 